name: fix build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: permission
      run: chmod +x gradlew

    - name: build
      run: ./gradlew assembleDebug

    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk
